pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Hello(2)') {
            steps {
                echo 'Hello World (2)'
            }
        }
        stage('Action') {
            steps {
                bat '''
                cd "p2\\src" & job.bat
                '''
            }
        }
    }


    post {
        always {
            archiveArtifacts artifacts: "p2\\p2\\src\\*pdf", fingerprint: true
        }
    }

}
